# Basic
title: 栾威杰
subtitle: 个人站
description: 欢迎来到我的个人站~
author: luanwj
# 头像里面的标题
avatarTitle: luanweijie
# 头像里面的描述
avatarDesc: java
url: "https://github.com/luanweijie"

# Comment
comment:
    # disqus: leopard
    # duoshuo: leopard 
    # cloudTie: leopard

# Social
social:
    weibo: 3948757700 
    github: luanweijie
    # twitter: 
    mail: lwj_json@163.com

 # 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 29b6d192c2fa6345a3f62fe7755d5cfa  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-102356360-1   
    host: auto  
#facebook login    
facebook:
    id: 2513253975362134
    apiversion: v3.2





# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/luanweijie
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


